const colors = {
  light: {
    text: "#ffffff",
    tint: "#FE2C55",
    background: "#000000",
    foreground: "#ffffff",
    card: "#111111",
    cardForeground: "#ffffff",
    primary: "#FE2C55",
    primaryForeground: "#ffffff",
    secondary: "#25F4EE",
    secondaryForeground: "#000000",
    muted: "#1C1C1C",
    mutedForeground: "#8A8B91",
    accent: "#FE2C55",
    accentForeground: "#ffffff",
    destructive: "#FF4444",
    destructiveForeground: "#ffffff",
    border: "#2C2C2C",
    input: "#2C2C2C",
  },
  dark: {
    text: "#ffffff",
    tint: "#FE2C55",
    background: "#000000",
    foreground: "#ffffff",
    card: "#111111",
    cardForeground: "#ffffff",
    primary: "#FE2C55",
    primaryForeground: "#ffffff",
    secondary: "#25F4EE",
    secondaryForeground: "#000000",
    muted: "#1C1C1C",
    mutedForeground: "#8A8B91",
    accent: "#FE2C55",
    accentForeground: "#ffffff",
    destructive: "#FF4444",
    destructiveForeground: "#ffffff",
    border: "#2C2C2C",
    input: "#2C2C2C",
  },
  radius: 10,
};

export default colors;
